/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import javax.swing.JOptionPane;
import java.util.Random;
import javax.swing.JButton;
import java.util.concurrent.ThreadLocalRandom;
/**
 *
 * @author ADMIN
 */
public class lab3 extends javax.swing.JFrame {

    /**
     * Creates new form lab3
     */
    public lab3() {
       initComponents();
        String m = JOptionPane.showInputDialog("Nhập Tên Người Chơi ");
        System.out.println(m);
        setTitle(m);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        batdau = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        so15 = new javax.swing.JButton();
        so14 = new javax.swing.JButton();
        so13 = new javax.swing.JButton();
        so12 = new javax.swing.JButton();
        so11 = new javax.swing.JButton();
        so10 = new javax.swing.JButton();
        so9 = new javax.swing.JButton();
        so8 = new javax.swing.JButton();
        so7 = new javax.swing.JButton();
        so6 = new javax.swing.JButton();
        so5 = new javax.swing.JButton();
        so4 = new javax.swing.JButton();
        so3 = new javax.swing.JButton();
        so2 = new javax.swing.JButton();
        so1 = new javax.swing.JButton();
        khoangtrang = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("                                                      BẮT ĐẦU");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("                 TRÒ CHƠI XẾP Ô SỐ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        batdau.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        batdau.setText("BẮT ĐẦU");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(batdau, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(batdau, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setLayout(new java.awt.GridLayout(4, 4));

        so15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        so15.setText("15");
        jPanel4.add(so15);

        so14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        so14.setText("14");
        jPanel4.add(so14);

        so13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        so13.setText("13");
        jPanel4.add(so13);

        so12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        so12.setText("12");
        jPanel4.add(so12);

        so11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        so11.setText("11");
        jPanel4.add(so11);

        so10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        so10.setText("10");
        jPanel4.add(so10);

        so9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        so9.setText("9");
        jPanel4.add(so9);

        so8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        so8.setText("8");
        jPanel4.add(so8);

        so7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        so7.setText("7");
        jPanel4.add(so7);

        so6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        so6.setText("6");
        jPanel4.add(so6);

        so5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        so5.setText("5");
        jPanel4.add(so5);

        so4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        so4.setText("4");
        jPanel4.add(so4);

        so3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        so3.setText("3");
        jPanel4.add(so3);

        so2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        so2.setText("2");
        jPanel4.add(so2);

        so1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        so1.setText("1");
        jPanel4.add(so1);

        khoangtrang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel4.add(khoangtrang);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void tronMang(int [] ar){
        Random rnd = ThreadLocalRandom.current();
        for(int i = ar.length-1;i>0;i--){
            int index = rnd.nextInt(i+1);
            int a = ar[index];
            ar[index] = ar[i];
            ar[i]=a;
        }
    }
private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        Sapxep2nut(so1, so2, so5);
        
    }//GEN-LAST:event_btn1ActionPerformed
    public void Sapxep3nut(JButton btnan , JButton btnvt0 , JButton btnvt1, JButton btnvt2){
        if(btnvt0.getText().length()==0){
            btnvt0.setText(btnan.getText());
            btnan.setText("");
        }
        if(btnvt1.getText().length()==0){
            btnvt1.setText(btnan.getText());
            btnan.setText("");
        }
        if(btnvt2.getText().length()==0){
            btnvt2.setText(btnan.getText());
            btnan.setText("");
        }
    }
     public void Sapxep2nut(JButton btnan , JButton btnvt0 , JButton btnvt1){
        if(btnvt0.getText().length()==0){
            btnvt0.setText(btnan.getText());
            btnan.setText("");
        }
        if(btnvt1.getText().length()==0){
            btnvt1.setText(btnan.getText());
            btnan.setText("");
        }
      
    }
      public void Sapxep4nut(JButton btnan , JButton btnvt0 , JButton btnvt1, JButton btnvt2,JButton btnvt3){
        if(btnvt0.getText().length()==0){
            btnvt0.setText(btnan.getText());
            btnan.setText("");
        }
        if(btnvt1.getText().length()==0){
            btnvt1.setText(btnan.getText());
            btnan.setText("");
        }
        if(btnvt2.getText().length()==0){
            btnvt2.setText(btnan.getText());
            btnan.setText("");
        }
        if(btnvt3.getText().length()==0){
            btnvt3.setText(btnan.getText());
            btnan.setText("");
        }
    }
    private void btn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn15ActionPerformed
        // TODO add your handling code here:
        Sapxep3nut(so15, so14, so11, khoangtrang);
    }//GEN-LAST:event_btn15ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        if(so15.getText().length()==0){
            so15.setText(khoangtrang.getText());
            khoangtrang.setText("");
        }
        if(so12.getText().length()==0){
            so12.setText(khoangtrang.getText());
            khoangtrang.setText("");
        }
        checkWin();
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn14ActionPerformed

        // TODO add your handling code here:
        Sapxep3nut(so4, so13, so10, so15);
        
    }//GEN-LAST:event_btn14ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        // TODO add your handling code here:
        Sapxep3nut(so12, so11, khoangtrang, so8);
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn13ActionPerformed
        // TODO add your handling code here:
        Sapxep2nut(so13, so9, so14);
    }//GEN-LAST:event_btn13ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        // TODO add your handling code here:
        Sapxep4nut(so11, so10, so7, so12, so15);
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        // TODO add your handling code here:
        Sapxep4nut(so10, so9, so6, so11, so14);
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        Sapxep3nut(so9, so5, so10, so13);
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        Sapxep3nut(so8, so7, so4, so12);
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        Sapxep4nut(so7, so6, so3, so8, so11);
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        Sapxep4nut(so6, so5, so2, so7, so10);
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        Sapxep3nut(so5, so1, so6, so9);
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        Sapxep2nut(so4, so3, so8);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        Sapxep3nut(so3, so2, so4, so7);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        Sapxep3nut(so2, so1, so3, so6);
    }//GEN-LAST:event_btn2ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        so1.setEnabled(true);
        so2.setEnabled(true);
        so3.setEnabled(true);
        so4.setEnabled(true);
        so5.setEnabled(true);
        so6.setEnabled(true);
        so7.setEnabled(true);
        so8.setEnabled(true);
        so9.setEnabled(true);
        so10.setEnabled(true);
        so11.setEnabled(true);
        so12.setEnabled(true);
        so13.setEnabled(true);
        so14.setEnabled(true);
        so15.setEnabled(true);
        khoangtrang.setEnabled(true);
       ganSo();
       khoangtrang.setText("");
       
    }//GEN-LAST:event_jButton17ActionPerformed
    public void ganSo(){
         int []a={1,2,3,4,5,6,7,8,9,10,11,12,13,14,15};
         tronMang(a);
         int num1 = a[0];
         so1.setText(""+num1);
         int num2 = a[1];
         so2.setText(""+num2);
         int num3 = a[2];
         so3.setText(""+num3);
         int num4 = a[3];
         so4.setText(""+num4);
         int num5 = a[4];
         so5.setText(""+num5);
         int num6 = a[5];
         so6.setText(""+num6);
         int num7 = a[6];
         so7.setText(""+num7);
         int num8 = a[7];
         so8.setText(""+num8);
         int num9 = a[8];
         so9.setText(""+num9);
         int num10 = a[9];
         so10.setText(""+num10);
         int num11 = a[10];
         so11.setText(""+num11);
         int num12 = a[11];
         so12.setText(""+num12);
         int num13 = a[12];
         so13.setText(""+num13);
         int num14 = a[13];
         so14.setText(""+num14);
         int num15 = a[14];
         so15.setText(""+num15);
         
         
    }
    public void checkWin(){
        if (so1.getText().equals("1")
                && so2.getText().equals("2")
                && so3.getText().equals("3")
                && so4.getText().equals("4")
                && so5.getText().equals("5")
                && so6.getText().equals("6")
                && so7.getText().equals("7")
                && so8.getText().equals("8")
                && so9.getText().equals("9")
                && so10.getText().equals("10")
                && so11.getText().equals("11")
                && so12.getText().equals("12")
                && so13.getText().equals("13")
                && so14.getText().equals("14")
                && so15.getText().equals("15")
                && khoangtrang.getText().equals("")
                ){
            JOptionPane.showMessageDialog(null, "Win");
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lab3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lab3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lab3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lab3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lab3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batdau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton khoangtrang;
    private javax.swing.JButton so1;
    private javax.swing.JButton so10;
    private javax.swing.JButton so11;
    private javax.swing.JButton so12;
    private javax.swing.JButton so13;
    private javax.swing.JButton so14;
    private javax.swing.JButton so15;
    private javax.swing.JButton so2;
    private javax.swing.JButton so3;
    private javax.swing.JButton so4;
    private javax.swing.JButton so5;
    private javax.swing.JButton so6;
    private javax.swing.JButton so7;
    private javax.swing.JButton so8;
    private javax.swing.JButton so9;
    // End of variables declaration//GEN-END:variables
}
